### ISSUE TITLE
일부 모드는 에러창 표시됨

### ISSUE THREAD

**Issue by steak002** [lazylee-l2i/minecraft-Mod-Translator#2]
우선 만들어줘서 고맙습니다.

파파고 버전으로 번역중인데 가끔 어떤 모드들은 아래 에러창 띄우면서 번역이 안되는데
해결방법이 있나요?
urllib.error.HTTPError: HTTP Error 400: Bad Reques

**Comment by lazylee-l2i** [comment]
만든지 기간이 꽤 지나서 레퍼런스를 찾아보느라 답변이 늦은 점 사과드립니다.
아래 몇 가지 사항을 확인해 주실 수 있을까요?
1. Naver API Key (Naver Cloud에서 Application 항목에서 확인 가능합니다.)
2. 마인크래프트 버전
3. Python 실행 오류인지 Papago API에서 리턴 된 오류인지
- 후자의 경우 Error Code : [에러 메세지]의 형식으로 출력됩니다.
4. 모드가 Forge 모드인지

답변주시는동안 저도 다시 한번 확인해보겠습니다.
이슈 공유 감사합니다.

+ 2024-05-06 20:36 추가사항
1.20.1 버전의 모드로 테스트해봤습니다.
이미 한국어화 파일이 있는 모드 / 한국어화 파일이 없는 모드
이미 한국어화가 진행 된 경우 jar 파일 내에 중복생성되는 문제는 있었지만 번역 자체는 정상적으로 진행되었습니다.
혹시라도 이 내용을 보셨다면 사용하시는 모드의 링크도 안내 부탁드리겠습니다.

**Comment by lazylee-l2i** [comment]
> 우선 만들어줘서 고맙습니다.
> 
> 파파고 버전으로 번역중인데 가끔 어떤 모드들은 아래 에러창 띄우면서 번역이 안되는데 해결방법이 있나요? urllib.error.HTTPError: HTTP Error 400: Bad Reques

17일까지 답변이 없으시다면 이슈 클로징 하겠습니다.

**Comment by lazylee-l2i** [comment]
장기간 미응답으로 클로징 하겠습니다.
