### ISSUE TITLE
파파고 버전 사용중입니다. 

### ISSUE THREAD

**Issue by ssw1279** [lazylee-l2i/minecraft-Mod-Translator#3]
70개 정도의 모듈을 전부 돌리려고 하니

Here is no Language file
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    run()
  File "main.py", line 61, in run
    je.allFile()
  File "main.py", line 27, in allFile
    self.oneFile(zip_path)
  File "main.py", line 16, in oneFile
    json_file, lang_path = self.postProcessing(_file=_file)
TypeError: cannot unpack non-iterable NoneType object

메세지와 함께
중간 중간 꺼집니다. 
명령어로 다시 키면 다음 모드부터 진행 되지만 
오류 발생시 넘어가지 않고 꺼집니다. 구글 버전은 잘 넘어가던데. 파파고는 안되는거 같습니다.

수동으로 해도 되지만.. 오류 같이 보여서 문의 남깁니다.

**Comment by lazylee-l2i** [comment]
늦게 확인하여 죄송합니다.
아래 사항을 저에게 알려주시면 감사하겠습니다.
1. Minecraft 버전
2. MC Mod 로더(ex. Forge)
3. Python 버전

추가로 Papago의 경우 본인이 보유한 API Key를 넣었는지도 확인 부탁드리겠습니다.
감사합니다.

**Comment by lazylee-l2i** [comment]
장기간 미응답으로 이슈 닫겠습니다

**Comment by lazylee-l2i** [comment]
장기간 미응답으로 이슈 닫겠습니다
